version: "3.7"

services:
  market_db:
    container_name: market_db
    build:
      context: ./db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

volumes:
  dbdata:

networks:
  market_networks: