version: "3"

services:
  market_fe:
    build:
      context: ./devcontainer
    working_dir: /workspace
    volumes:
      - ../marketFe/market-fe:/workspace:cached
      - ./.vscode:/workspace/.vscode:cached
    tty: true
    ports:
      - "8000:8000"
    networks:
      - market_networks

volumes:
  node-modules:

networks:
  market_networks: