version: "3"

services:
  market_fe:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14
    working_dir: /workspace
    volumes:
      - ../marketFe/market-fe:/workspace:cached
      - ./.vscode:/workspace/.vscode:cached
    tty: true
    ports:
      - "8081:8080"
    networks:
      - market_networks

volumes:
  node-modules:

networks:
  market_networks: