# spring.application.name: marketBe

mybatis:
  type-aliases-package: eunbi.kwon.marketBe.model
  configuration:
    map-underscore-to-camel-case: true
  # config-location: classpath:/mybatis/mybatis-config.xml

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/market
    username: postgres
    password: password
    mapper-locations: classpath:/mapper/**/*.xml